### PR TITLE
Zach community description

### PR DESCRIPTION
**Pull request by ZachBourque**
# Description

This PR includes the following proposed change(s):

- Changed the way Community rules are input in both EditCommunityModal and AddCommunutyModal
- Added Markdown capabilities to community description
- Created a MarkDownDisplay component to render markdown 
- Added InputRuleList.jsx and RuleInput.jsx to change how rule creation works
- Changed communityDuck's editCommunity function to take in a community name and a changes object seperately

## Requires

Add 'Requires Attention' label if appropriate.

- [ ] Requires an update to the .env file
- [ ] Requires adding a file listed in the .gitignore
- [ ] Requires an opinion or answer to a question, see comments.
- [ ] Requires other attention, see below.

If there are any requirements for the developer to make after this PR is merged please list them here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

For pull requests that are not just a simple fix, please check that the branch works on your local machine.

- [x] Tested by Zach.
- [ ] Tested by Brandon.
- [ ] Tested by Brady.

## Does the change impact or break the Docker build?

- [ ] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] If attention is required by the developer such as updating the .env file, these requirements have been listed.

### CODE REVIEW

**Review by BradyMitch — APPROVED** [review]
Approved. Please test my tweaks before merging.

**Comment by ZachBourque** [comment]
> Made some tweaks.
> 
> * Changed Community card on Communities page to use MD Display.
> * Added rule length checks before showing save button on add rule.
> * Cancel rule button deletes the rule if fields are left empty.
> * Add rule by default will open the edit textfields.
> * By default, rule 1 will not be displayed in the modal. You must click "Add Rule +".
> * Changed community modals so rules isn't required.

I personally am not a fan of the cancel button in RuleInput.jsx doing two different things. I see the intent but I feel like the actions of the buttons should stay consistent, even if we're trying to guide the user to use this component correctly.

@Bottle7 thoughts?

**Comment by BradyMitch** [comment]
> > Made some tweaks.
> > 
> > * Changed Community card on Communities page to use MD Display.
> > * Added rule length checks before showing save button on add rule.
> > * Cancel rule button deletes the rule if fields are left empty.
> > * Add rule by default will open the edit textfields.
> > * By default, rule 1 will not be displayed in the modal. You must click "Add Rule +".
> > * Changed community modals so rules isn't required.
> 
> I personally am not a fan of the cancel button in RuleInput.jsx doing two different things. I see the intent but I feel like the actions of the buttons should stay consistent, even if we're trying to guide the user to use this component correctly.
> 
> @Bottle7 thoughts?

I think it's weird having it display an empty rule when you cancel. The thought was that you start creating a rule and then cancel it, it should remove the rule you were about to create.

**Comment by Bottle7** [comment]
> > Made some tweaks.
> > 
> > * Changed Community card on Communities page to use MD Display.
> > * Added rule length checks before showing save button on add rule.
> > * Cancel rule button deletes the rule if fields are left empty.
> > * Add rule by default will open the edit textfields.
> > * By default, rule 1 will not be displayed in the modal. You must click "Add Rule +".
> > * Changed community modals so rules isn't required.
> 
> I personally am not a fan of the cancel button in RuleInput.jsx doing two different things. I see the intent but I feel like the actions of the buttons should stay consistent, even if we're trying to guide the user to use this component correctly.
> 
> @Bottle7 thoughts?

Relabel the button to 'Discard' or 'Discard Rule'

**Comment by BradyMitch** [comment]
> > > Made some tweaks.
> > > 
> > > * Changed Community card on Communities page to use MD Display.
> > > * Added rule length checks before showing save button on add rule.
> > > * Cancel rule button deletes the rule if fields are left empty.
> > > * Add rule by default will open the edit textfields.
> > > * By default, rule 1 will not be displayed in the modal. You must click "Add Rule +".
> > > * Changed community modals so rules isn't required.
> > 
> > 
> > I personally am not a fan of the cancel button in RuleInput.jsx doing two different things. I see the intent but I feel like the actions of the buttons should stay consistent, even if we're trying to guide the user to use this component correctly.
> > @Bottle7 thoughts?
> 
> Relabel the button to 'Discard' or 'Discard Rule'

Maybe its a conditional, if rule doesn't meet the min length requirement it will display "Discard", else it will display cancel.

**Pull request merged**
