### PR TITLE
HWP-426 Create Splash Page

### PR DESCRIPTION
**Pull request by ZachBourque**
# Description

This PR includes the following proposed change(s):

- Overhaul of LoginPage.jsx
- Login route now leads to keycloak login route

## Requires

Add 'Requires Attention' label if appropriate.

- [ ] Requires an update to the .env file
- [ ] Requires adding a file listed in the .gitignore
- [ ] Requires an opinion or answer to a question, see comments.
- [ ] Requires other attention, see below.

If there are any requirements for the developer to make after this PR is merged please list them here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

For pull requests that are not just a simple fix, please check that the branch works on your local machine.

- [x] Tested by Zach.
- [ ] Tested by Brandon.
- [ ] Tested by Brady.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] If attention is required by the developer such as updating the .env file, these requirements have been listed.

### CODE REVIEW

**Comment by BradyMitch** [comment]
@ZachBourque What about when TOGGLE_KEYCLOAK_AUTH isn't set or is false?

**Comment by ZachBourque** [comment]
> @ZachBourque What about when TOGGLE_KEYCLOAK_AUTH isn't set or is false?

Because of the difficulty of getting env variables into the frontend, for the time being I put a DO NOT MERGE label on this PR and we will not merge it until it is ready.

**Comment by BradyMitch** [comment]
Looks good but my 100% browser zoom messes up the display. We need to tweak the responsiveness.

**Review by BradyMitch — APPROVED** [review]
Thanks for making the responsiveness changes for my screen size!

**Pull request merged**
